Repository tehnoroboty/InstaProgect, pull requests merged in 2025-01, with the labels that each got.

#23 SCRUM-22 feat: add input
  src/assets/componentsIcons/CloseOutline.tsx
  src/assets/componentsIcons/EyeOffOutline.tsx
  src/assets/componentsIcons/EyeOutline.tsx
  src/assets/componentsIcons/SearchOutline.tsx
  src/components/input/Input.module.scss
  src/components/input/Input.stories.tsx
  src/components/input/Input.tsx
  src/components/input/index.ts
Labels: review

#29 add disable for label
  src/components/typography/Typography.stories.tsx
  src/components/typography/Typography.tsx
  src/components/typography/typography.module.scss
Labels: in progress

#28 SCRUM-13/select refactoring, replace icons
  .idea/prettier.xml
  src/assets/componentsIcons/ArrowIosDownOutline.tsx
  src/assets/componentsIcons/Flagrussia.tsx
  src/assets/componentsIcons/Flagunitedkingdom.tsx
  src/components/header/header-web/HeaderWeb.tsx
  src/components/select/Select.module.scss
  src/components/select/SelectBox.stories.ts
  src/components/select/SelectBox.tsx
  src/components/select/SelectItem.tsx
  src/components/select/SelectLanguage/SelectLanguage.stories.ts
  src/components/select/SelectLanguage/SelectLanguage.tsx
  src/components/selectBox/SelectBox.tsx
  src/components/selectBox/SelectIcon.tsx
  src/components/selectBox/SelectLanguage/SelectIconRu.tsx
  src/components/selectBox/SelectLanguage/SelectIconUk.tsx
Labels: review

#27 SCRUM-22/Input fix: change styles
  src/components/input/Input.module.scss
  src/components/input/Input.stories.tsx
  src/components/input/Input.tsx
  src/components/text-area/TextArea.stories.ts
  src/components/text-area/TextArea.stories.tsx
  src/components/text-area/TextArea.tsx
  src/components/text-area/textArea.module.scss
Labels: in progress

#31 Scrum 13/ add JSDoc comments to props
  src/components/select/SelectBox.stories.ts
  src/components/select/SelectBox.tsx
  src/components/select/SelectLanguage/SelectLanguage.tsx
Labels: review

#26 change textarea
  src/components/text-area/TextArea.stories.tsx
  src/components/textArea/TextArea.stories.tsx
  src/components/textArea/TextArea.tsx
  src/components/textArea/textArea.module.scss
Labels: in progress

#37 some changes
  package.json
  pnpm-lock.yaml
  src/components/select/SelectItem.tsx
Labels: in progress

#40 add jsDocs
  src/components/typography/Typography.tsx
Labels: review

#42 Scrum 6/alerts
  src/components/alerts/Alerts.stories.ts
  src/components/alerts/Alerts.tsx
  src/components/alerts/alerts.module.scss
Labels: in progress, review

#41 Scrum 35/ add styles to select for pagination and className prop to selectBox
  src/components/select/Select.module.scss
  src/components/select/SelectBox.stories.ts
  src/components/select/SelectBox.tsx
  src/components/select/SelectItem.tsx
  src/components/select/SelectLanguage/SelectLanguage.tsx
Labels: review

#43 SCRUM-37 feat: adding responsiveness to the panel navigation
  src/app/layout.tsx
  src/components/checkbox/checkBox.module.scss
  src/components/header/Header.stories.tsx
  src/components/header/Header.tsx
  src/components/header/header-mob/HeaderMobile.tsx
  src/components/header/header-mob/dropdown-menu/DropdownMenu.tsx
  src/components/header/header-mob/dropdown-menu/dropdownMenu.module.scss
  src/components/header/header.module.scss
  src/components/itemWrapper/ItemWrapper.tsx
  src/components/itemWrapper/itemWrapper.module.scss
  src/components/navigationPanel/NavigationPanel.stories.ts
  src/components/navigationPanel/NavigationPanel.tsx
  src/components/navigationPanel/menuMobile/MenuMobile.tsx
  src/components/navigationPanel/menuMobile/menuMobile.module.scss
  src/components/navigationPanel/sidebar/Sidebar.stories.ts
  src/components/navigationPanel/sidebar/Sidebar.tsx
  src/components/navigationPanel/sidebar/menuSection/MenuSection.tsx
  src/components/navigationPanel/sidebar/sidebar.module.scss
  src/components/radioGroup/RadioBtn.stories.tsx
  src/components/radioGroup/radioBtn.module.scss
  src/components/sidebar/Sidebar.stories.ts
  src/hooks/useMobile.ts
  src/styles/_boilerplate.scss
Labels: review

#48 feat: create Card component
  src/components/card/Card.stories.ts
  src/components/card/Card.tsx
  src/components/card/card.module.scss
Labels: review

#47 Scrum 38
  src/components/alerts/Alerts.tsx
  src/components/button/Button.stories.ts
  src/components/button/Button.tsx
  src/components/button/button.module.scss
Labels: review

#45 SCRUM-32 fix: update ReCAPTCHA
  .env.local
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/recaptcha/Recaptcha.stories.ts
  src/components/recaptcha/Recaptcha.tsx
  src/components/recaptcha/recaptcha.module.scss
  src/utils/recaptchaGetKey.ts
Labels: review

#49 SCRUM-39 init: structura and store
  .env.local
  package.json
  pnpm-lock.yaml
  src/app/(account)/home/page.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/registration/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/header/header.module.scss
  src/store/StoreWrapper.tsx
  src/store/services/authApi.ts
  src/store/store.ts
Labels: review

#46 feat: adding component for OAuth2
  .env.local
  pnpm-lock.yaml
  src/app/(auth)/github/page.tsx
  src/app/(auth)/google/page.tsx
  src/components/oauthbuttons/OAuthButtons.stories.tsx
  src/components/oauthbuttons/OAuthButtons.tsx
  src/components/oauthbuttons/githubOAuthButton/GitHubOAuthButton.tsx
  src/components/oauthbuttons/githubOAuthButton/gitHubOAuthButton.module.scss
  src/components/oauthbuttons/googleOAuthButton/GoogleOAuthButton.tsx
  src/components/oauthbuttons/oAuthButton.module.scss
  src/store/services/authApi.ts
  src/utils/googleClientId.ts
Labels: in progress
