Repository tehnoroboty/InstaProgect, pull requests merged in 2025-03, with the labels that each got.

#116 SCRUM-71: add Story to ModalCommentsSection
  src/shared/ui/postLikesBox/PostLikesBox.tsx
  src/widgets/commentsSection/ModalCommentsSection.stories.tsx
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/interactionBar/InteractionBar.tsx
Labels: review

#120 Scrum 75 renewed public post (and carousel fixes)
  pnpm-lock.yaml
  src/entities/posts/types.ts
  src/shared/ui/carousel/Carousel.tsx
  src/shared/ui/carousel/carousel.module.scss
  src/shared/ui/carousel/carousel.stories.tsx
  src/widgets/publicFeedPost/PublicFeedPost.stories.tsx
  src/widgets/publicFeedPost/PublicFeedPost.tsx
  src/widgets/publicFeedPost/publicFeedPost.module.scss
Labels: review

#119 Scrum 54 add
  next.config.mjs
  package.json
  pnpm-lock.yaml
  scripts/getCroppedImage.js
  src/features/createPost/CreatePost.tsx
  src/features/createPost/createPost.module.scss
  src/features/croppingPhoto/CroppingPhoto.tsx
  src/features/croppingPhoto/applyCropToAllPhotos.ts
  src/features/croppingPhoto/croppingPhoto.module.scss
  src/features/croppingPhoto/photoPreview/PhotoPreview.tsx
  src/features/croppingPhoto/photoPreview/photoPreview.module.scss
  src/features/croppingPhoto/sizeBox/SizeBox.tsx
  src/features/croppingPhoto/sizeBox/sizeBox.module.scss
  src/features/croppingPhoto/types.ts
  src/features/filteringPhoto/FilteringPhoto.tsx
  src/features/filteringPhoto/filteringPhoto.module.scss
  src/features/publishPhoto/PublishPhoto.tsx
  src/features/publishPhoto/publishPhoto.module.scss
  src/shared/assets/componentsIcons/ArrowIosBackOutline.tsx
  src/shared/assets/componentsIcons/ExpandOutline.tsx
  src/shared/assets/componentsIcons/Image.tsx
  src/shared/assets/componentsIcons/Maximize.tsx
  src/shared/assets/componentsIcons/MaximizeOutline.tsx
  src/shared/assets/componentsIcons/PlusCircleOutline.tsx
  src/shared/assets/icons/image.svg
  src/shared/hooks/useBoolean.ts
  src/shared/lib/constants/regex.ts
  src/shared/ui/carousel/Carousel.tsx
  src/shared/ui/popover/Popover.tsx
  src/shared/ui/slider/Slider.tsx
  src/shared/ui/slider/slider.module.scss
  src/widgets/addPost/AddPost.tsx
  src/widgets/addPost/data.ts
  src/widgets/exitModal/ExitModal.tsx
  src/widgets/exitModal/exitModal.module.scss
Labels: in progress

#123 Scrum 86 Feat: create modal post dialog
  src/shared/ui/dialog/Dialog.tsx
  src/shared/ui/dropdown/dropdown.module.scss
  src/widgets/commentsSection/ModalCommentsSection.stories.tsx
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/commentsSection/modalCommentsSection.module.scss
  src/widgets/modalPost/ModalPost.stories.tsx
  src/widgets/modalPost/ModalPost.tsx
  src/widgets/modalPost/assets/slider.jpg
  src/widgets/modalPost/modalPost.module.scss
  src/widgets/postComments/ModalPostComments.stories.tsx
  src/widgets/postComments/ModalPostComments.tsx
  src/widgets/postComments/assets/slider.jpg
  src/widgets/postComments/modalPostComments.module.scss
Labels: review

#118 SCRUM-57 feat: create postsApi
  next.config.mjs
  src/shared/model/api/postsApi.ts
  src/shared/model/api/types.ts
  src/shared/ui/postsGrid/Posts.tsx
  src/shared/ui/postsGrid/posts.module.scss
  src/widgets/profile/Profile.tsx
  src/widgets/profile/myProfile.module.scss
Labels: in progress

#128 SCRUM-89: change focus style to icons in ModalCommentsSection
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/commentsSection/modalCommentsSection.module.scss
  src/widgets/interactionBar/InteractionBar.tsx
  src/widgets/interactionBar/interactionBar.module.scss
Labels: review

#127 SCRUM-54 init: create newPost
  src/app/posts/page.tsx
  src/features/croppingPhoto/CroppingPhoto.tsx
  src/features/croppingPhoto/croppingPhoto.module.scss
  src/features/filteringPhoto/FilteringPhoto.tsx
  src/features/forgotPassword/ForgotPasswordCard.tsx
  src/features/publishPhoto/PublishPhoto.tsx
  src/features/publishPhoto/hooks/uploadPhoto.ts
  src/features/publishPhoto/publishPhoto.module.scss
  src/shared/model/api/postsApi.ts
  src/shared/model/api/types.ts
  src/shared/ui/alerts/alerts.module.scss
  src/widgets/itemWrapper/ItemWrapper.tsx
  src/widgets/navigationPanel/NavigationPanel.tsx
  src/widgets/navigationPanel/sidebar/menuSection/MenuSection.tsx
Labels: review

#131 Scrum 90.1fix:fixed bugs
  src/shared/ui/carousel/Carousel.tsx
  src/shared/ui/carousel/carousel.stories.tsx
Labels: review, important

#138 SCRUM-95
  src/shared/ui/textAreaWithValidation/TextAreaWithValidation.stories.tsx
  src/shared/ui/textAreaWithValidation/TextAreaWithValidation.tsx
Labels: review

#135 SCRUM-57 feat
  pnpm-lock.yaml
  src/app/public/page.tsx
  src/app/public/profile/[userId]/page.tsx
  src/entities/user/types.ts
  src/shared/assets/componentsIcons/Image.tsx
  src/shared/assets/componentsIcons/ImageNotFound.tsx
  src/shared/assets/icons/image-not-found.svg
  src/shared/model/api/postsApi.ts
  src/shared/model/api/types.ts
  src/shared/model/api/usersApi.ts
  src/shared/styles/_boilerplate.scss
  src/shared/ui/carousel/Carousel.tsx
  src/shared/ui/dialog/Dialog.tsx
  src/shared/ui/postLikesBox/PostLikesBox.tsx
  src/shared/ui/postsGrid/Posts.tsx
  src/shared/ui/postsGrid/posts.module.scss
  src/widgets/commentsSection/modalCommentsSection.module.scss
  src/widgets/modalPost/ModalPost.tsx
  src/widgets/modalPost/modalPost.module.scss
  src/widgets/profile/Profile.tsx
  src/widgets/profile/PublicProfile/PublicProfile.tsx
  src/widgets/profile/PublicProfile/profileInfo/ProfileInfo.tsx
  src/widgets/profile/PublicProfile/profileInfo/profileInfo.module.scss
  src/widgets/profile/myProfile.module.scss
  src/widgets/profile/profileInfo/ProfileInfo.tsx
  src/widgets/profile/profileInfo/profileInfo.module.scss
  tsconfig.json
Labels: in progress

#130 SCRUM-55: create EditPost component
  src/shared/assets/componentsIcons/CloseOutline.tsx
  src/shared/model/api/postsApi.ts
  src/shared/model/api/types.ts
  src/shared/ui/dialog/Dialog.tsx
  src/shared/ui/userAvatarName/UserAvatarName.tsx
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/commentsSection/modalCommentsSection.module.scss
  src/widgets/dropdownPost/DropdownPost.tsx
  src/widgets/editPost/EditPost.tsx
  src/widgets/editPost/editPost.module.scss
  src/widgets/editPost/сonfirmationModal/ConfirmationModal.tsx
  src/widgets/editPost/сonfirmationModal/сonfirmationModal.module.scss
  src/widgets/modalPost/ModalPost.tsx
Labels: in progress

#142 SCRUM-57 fix: fix
  src/shared/ui/avatar/AvatarBox.tsx
  src/shared/ui/dialog/dialog.module.scss
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/commentsSection/modalCommentsSection.module.scss
  src/widgets/modalPost/modalPost.module.scss
  src/widgets/profile/Profile.tsx
Labels: in progress

#143 Scrum 55: some corrections
  src/shared/model/api/postsApi.ts
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/editPost/EditPost.tsx
  src/widgets/editPost/editPost.module.scss
  src/widgets/modalPost/ModalPost.tsx
Labels: review

#144 SCRUM-57 new logic
  src/app/profile/[userId]/page.tsx
  src/app/profile/[userId]/settings/page.tsx
  src/app/public/page.tsx
  src/app/public/profile/[userId]/page.tsx
  src/features/publishPhoto/PublishPhoto.tsx
  src/shared/model/api/baseApi.ts
  src/shared/model/api/followingApi.ts
  src/shared/model/api/postsApi.ts
  src/shared/model/api/types.ts
  src/shared/model/api/usersApi.ts
  src/widgets/SettingaPage.tsx
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/modalPost/ModalPost.tsx
  src/widgets/profile/Profile.tsx
  src/widgets/profile/PublicProfile/PublicProfile.tsx
  src/widgets/profile/PublicProfile/profileInfo/ProfileInfo.tsx
  src/widgets/profile/PublicProfile/profileInfo/profileInfo.module.scss
  src/widgets/profile/getPublicProfile.ts
  src/widgets/profile/myProfile.module.scss
  src/widgets/profile/profileInfo/ProfileInfo.tsx
Labels: in progress

#145 SCRUM-98: some refactoring
  src/features/croppingPhoto/CroppingPhoto.tsx
  src/features/filteringPhoto/FilteringPhoto.tsx
  src/features/publishPhoto/PublishPhoto.tsx
  src/features/publishPhoto/publishPhoto.module.scss
  src/shared/lib/constants/routing.ts
  src/shared/ui/select/Select.module.scss
  src/shared/ui/select/SelectBox.stories.ts
  src/shared/ui/select/SelectBox.tsx
Labels: in progress, review
