Repository tehnoroboty/InstaProgect, pull requests merged in 2025-04, with the labels that each got.

#148 SCRUM-104 feat: make scroll with lib react-intersection-observer
  package.json
  pnpm-lock.yaml
  src/widgets/profile/Profile.tsx
  src/widgets/profile/myProfile.module.scss
Labels: review, important

#147 Scrum settings
  package.json
  pnpm-lock.yaml
  src/app/(legal-docs)/data.ts
  src/app/(legal-docs)/pageStyle.module.scss
  src/app/(legal-docs)/privacy-policy/page.tsx
  src/app/(legal-docs)/terms-of-service/page.tsx
  src/app/profile/[userId]/settings/page.tsx
  src/entities/user/types.ts
  src/features/avatarContainerSettings/AvatarContainerSettings.tsx
  src/features/avatarContainerSettings/avatarContainerSettings.module.scss
  src/features/register/Register.tsx
  src/shared/assets/componentsIcons/CalendarOutline.tsx
  src/shared/lib/constants/error-messages.ts
  src/shared/lib/constants/regex.ts
  src/shared/model/api/baseApi.ts
  src/shared/model/api/usersApi.ts
  src/shared/ui/calendar/Calendar.tsx
  src/shared/ui/datePicker/DatePicker.tsx
  src/shared/ui/datePicker/datePicker.module.scss
  src/shared/ui/input/Input.module.scss
  src/shared/ui/input/Input.tsx
  src/shared/ui/select/SelectBox.tsx
  src/shared/ui/tabs/Tabs.stories.tsx
  src/shared/ui/textArea/TextArea.tsx
  src/widgets/SettingaPage.tsx
  src/widgets/generationInformation/GenerationInformation.tsx
  src/widgets/generationInformation/generationInformation.module.scss
  src/widgets/generationInformation/hooks/fetchCountriesAndCities.ts
  src/widgets/generationInformation/hooks/useAvatar.ts
  src/widgets/generationInformation/hooks/useCountryCityData.ts
  src/widgets/generationInformation/hooks/useDateSelection.ts
  src/widgets/generationInformation/validators.ts
  src/widgets/settingsInputs/ProfileInputsSettings.tsx
  src/widgets/settingsPage/SettingaPage.tsx
  src/widgets/settingsPage/data.ts
  src/widgets/settingsPage/settingsPage.module.scss
Labels: in progress

#151 SCRUM105: styles for calendar
  src/shared/assets/componentsIcons/ArrowIosBackOutline.tsx
  src/shared/assets/componentsIcons/ArrowIosForwardOutline.tsx
  src/shared/ui/calendar/Calendar.tsx
  src/shared/ui/calendar/calendar.module.scss
  src/shared/ui/datePicker/datePicker.module.scss
Labels: in progress

#152 SCRUM-106 init: devices page
  src/entities/devices.ts
  src/shared/assets/componentsIcons/Chrome.tsx
  src/shared/assets/componentsIcons/Desktop.tsx
  src/shared/assets/componentsIcons/Mobile.tsx
  src/shared/assets/componentsIcons/index.ts
  src/shared/assets/icons/chrome-svgrepo-com.svg
  src/shared/assets/icons/desktop_mac.svg
  src/shared/assets/icons/phone_iphone.svg
  src/shared/model/api/baseApi.ts
  src/shared/model/api/devicesApi.ts
  src/widgets/devices/Devices.tsx
  src/widgets/devices/devices.module.scss
  src/widgets/settingsPage/SettingaPage.tsx
Labels: in progress

#154 SCRUM-112 feat: create table ui
  src/entities/subscription/types.ts
  src/shared/lib/constants/subscriptions.ts
  src/shared/ui/table/Table.stories.tsx
  src/shared/ui/table/Table.tsx
  src/shared/ui/table/index.ts
  src/shared/ui/table/mockData.ts
  src/shared/ui/table/table.module.scss
  src/widgets/accountManager/AccountManagement.tsx
  src/widgets/myPayments/MyPayments.tsx
  src/widgets/myPayments/myPayments.module.scss
  src/widgets/settingsPage/SettingaPage.tsx
Labels: review

#155 SCRUM-16: Pagination
  src/shared/lib/constants/pagination.ts
  src/shared/ui/pagination/Pagination.stories.tsx
  src/shared/ui/pagination/Pagination.tsx
  src/shared/ui/pagination/pagination.module.scss
  src/shared/ui/pagination/usePagination.ts
  src/widgets/myPayments/MyPayments.tsx
  src/widgets/myPayments/myPayments.module.scss
Labels: review

#159 Scrum 114 profile info and follow unfollow
  src/entities/user/types.ts
  src/shared/model/api/usersApi.ts
  src/widgets/profile/Profile.tsx
  src/widgets/profile/profileInfo/ProfileInfo.tsx
Labels: review

#160 SCRUM-113 fix: fix create post and change profile photo
  src/features/createPost/CreatePostPhoto.tsx
  src/features/croppingPhoto/CroppingPhoto.tsx
  src/features/filteringPhoto/FilteringPhoto.tsx
  src/features/publishPhoto/PublishPhoto.tsx
  src/shared/model/api/usersApi.ts
  src/widgets/navigationPanel/NavigationPanel.tsx
Labels: review

#161 SCRUM-109: feat: creat canceled auto renewal
  src/features/login/Login.tsx
  src/features/register/Register.tsx
  src/shared/model/api/authApi.ts
  src/shared/model/api/baseApi.ts
  src/shared/model/api/subscriptionsApi.ts
  src/shared/ui/dialog/Dialog.tsx
  src/widgets/accountManager/AccountManagement.tsx
  src/widgets/generationInformation/GenerationInformation.tsx
  src/widgets/itemWrapper/ItemWrapper.tsx
  src/widgets/navigationPanel/sidebar/Sidebar.tsx
  src/widgets/navigationPanel/sidebar/menuSection/MenuSection.tsx
  src/widgets/profile/Profile.tsx
  src/widgets/profile/getPublicProfile.ts
Labels: review

#126 SCRUM-63: Public page
  src/app/page.tsx
  src/features/authWrapper/AuthWrapper.tsx
  src/shared/model/api/types.ts
  src/shared/model/store/store.ts
  src/shared/ui/card/card.module.scss
  src/shared/ui/postLikesBox/PostLikesBox.tsx
  src/widgets/commentsSection/ModalCommentsSection.tsx
  src/widgets/modalPost/ModalPost.tsx
  src/widgets/publicFeed/PublicFeed.tsx
  src/widgets/publicFeed/getPublicPosts.ts
  src/widgets/publicFeed/publicFeed.module.scss
  src/widgets/publicFeedPost/PublicFeedPost.stories.tsx
  src/widgets/publicFeedPost/PublicFeedPost.tsx
  src/widgets/publicFeedPost/publicFeedPost.module.scss
Labels: in progress
