Repository tehnoroboty/InstaProgect, pull requests merged in 2025-02, with the labels that each got.

#52 SCRUM-27 init: create registration page
  public/image/bro.svg
  public/image/rafiki.svg
  src/app/(auth)/registration/page.tsx
  src/app/auth/(legal-docs)/data.ts
  src/app/auth/(legal-docs)/pageStyle.module.scss
  src/app/auth/(legal-docs)/privacy-policy/page.tsx
  src/app/auth/(legal-docs)/terms-of-service/page.tsx
  src/app/auth/forgot-password/page.tsx
  src/app/auth/github/page.tsx
  src/app/auth/google/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/registration-confirmation/email-confirmed.module.scss
  src/app/auth/registration-confirmation/page.tsx
  src/app/auth/registration-email-resending/link-expired.module.scss
  src/app/auth/registration-email-resending/page.tsx
  src/app/auth/registration/page.tsx
  src/app/auth/registration/registration.module.scss
  src/assets/componentsIcons/ArrowBackOutline.tsx
  src/components/checkbox/CheckBox.tsx
  src/hooks/useMobile.ts
  src/store/services/authApi.ts
  src/store/services/types.ts
  src/styles/_boilerplate.scss
Labels: in progress

#50 SCRUM-29 init: start forgot password page
  src/app/auth/forgot-password/forgotPassword.module.scss
  src/app/auth/forgot-password/page.tsx
  src/app/auth/recovery/createNewPasswordPage.module.scss
  src/app/auth/recovery/page.tsx
  src/components/itemWrapper/ItemWrapper.tsx
  src/components/recaptcha/Recaptcha.tsx
  src/store/services/authApi.ts
  src/store/services/types.ts
Labels: in progress

#60 fix: correct redirect path in RegistrationСonfirmationPage
  src/app/auth/registration-confirmation/page.tsx
Labels: review

#51 SCRUM-28 feat: Login make design
  src/app/auth/login/page.module.scss
  src/app/auth/login/page.tsx
  src/components/alerts/Alerts.tsx
  src/components/input/Input.module.scss
  src/components/input/Input.tsx
  src/store/Slices/appSlice.ts
  src/store/services/authApi.ts
  src/store/services/baseApi.ts
  src/store/store.ts
  src/utils/handleError.ts
Labels: in progress

#64 fix: fixed error withe breakpoint
  src/components/header/Header.tsx
  src/components/header/header-mob/headerMobile.module.scss
  src/components/header/header-web/headerWeb.module.scss
  src/components/navigationPanel/NavigationPanel.tsx
  src/components/navigationPanel/menuMobile/menuMobile.module.scss
  src/components/navigationPanel/sidebar/sidebar.module.scss
  src/hooks/useMobile.ts
Labels: review

#65 feat: added error window to all pages
  src/app/auth/login/page.tsx
  src/app/layout.tsx
  src/components/alerts/Alerts.tsx
  src/components/alerts/CommonAlert.tsx
Labels: review

#63 SCRUM-30: feat LOGOUT
  src/components/itemWrapper/ItemWrapper.tsx
  src/store/services/authApi.ts
  src/store/services/baseApi.ts
  src/utils/apiErrorHandlers.ts
Labels: in progress

#69 SCRUM-48 fix: Login
  src/app/auth/login/page.module.scss
  src/app/auth/login/page.tsx
  src/features/Sinin/Signin.module.scss
  src/features/Sinin/Signin.tsx
  src/features/Sinin/index.ts
  src/features/Sinin/validators.ts
  src/store/services/types.ts
Labels: review

#68 Create pasword component
  src/app/auth/recovery/page.tsx
  src/app/google/page.tsx
  src/features/createNewPassword/CreateNewPasswordCard.tsx
  src/features/createNewPassword/createNewPasswordPage.module.scss
Labels: review

#70 Scrum 47: refactoring registration
  src/app/auth/registration-confirmation/page.tsx
  src/app/auth/registration-email-resending/page.tsx
  src/app/auth/registration/page.tsx
  src/features/link-expired-form/LinkExpiredForm.tsx
  src/features/link-expired-form/link-expired.module.scss
  src/features/registration-confirmation-form/RegistrationConfirmationForm.tsx
  src/features/registration-confirmation-form/email-confirmed.module.scss
  src/features/registration-form/RegistrationForm.tsx
  src/features/registration-form/registration.module.scss
  src/hooks/useRegistration.ts
  src/hooks/useRegistrationConfirmation.ts
  src/hooks/useRegistrationEmailResending.ts
  src/store/services/authApi.ts
  src/store/services/types.ts
Labels: review

#66 SCRUM-31 feat: adding error processing
  src/app/auth/github/page.tsx
  src/app/auth/google/page.tsx
  src/components/oauthbuttons/OAuthButtons.tsx
  src/components/oauthbuttons/githubOAuthButton/GitHubOAuthButton.tsx
  src/components/oauthbuttons/googleOAuthButton/GoogleOAuthButton.tsx
  src/store/services/authApi.ts
  src/store/services/types.ts
Labels: in progress

#75 SCRUM-52: replace uk-flag icon with a new one
  src/assets/componentsIcons/Flagrussia.tsx
  src/assets/componentsIcons/FlagunitedkingdomNew.tsx
  src/assets/componentsIcons/PaypalSvgrepoCom4.tsx
  src/components/header/header-web/headerWeb.module.scss
  src/components/select/Select.module.scss
  src/components/select/SelectLanguage/SelectLanguage.tsx
Labels: review

#74 SCRUM-49 fix:change error display
  src/features/createNewPassword/hooks/useCreateNewPassword.ts
  src/features/forgotPassword/ForgotPasswordCard.tsx
  src/features/forgotPassword/hooks/useForgotPasswordCard.ts
  src/features/registration-form/hooks/useRegistrationForm.ts
Labels: review

#78 Scrum 44
  package.json
  pnpm-lock.yaml
  src/app/auth/github/page.tsx
  src/app/auth/google/page.tsx
  src/app/layout.tsx
  src/components/progressBar/ProgressBar.tsx
  src/styles/_boilerplate.scss
Labels: review

#87 SCRUM-59 fix: update errors
  .env.local
  .env.production
  src/app/auth/google/page.tsx
  src/components/oauthbuttons/githubOAuthButton/GitHubOAuthButton.tsx
  src/components/oauthbuttons/googleOAuthButton/GoogleOAuthButton.tsx
  src/features/createNewPassword/hooks/useCreateNewPassword.ts
  src/features/forgotPassword/hooks/useForgotPasswordCard.ts
  src/features/link-expired-form/LinkExpiredForm.tsx
  src/features/link-expired-form/hooks/useLinkExpiredForm.ts
  src/features/login/Login.tsx
  src/features/login/hooks/useLogin.ts
  src/features/login/validators.ts
  src/features/registration-form/RegistrationForm.tsx
  src/features/registration-form/hooks/useRegistrationForm.ts
  src/features/registration-form/validators.ts
  src/store/services/types.ts
  src/utils/handleError.ts
Labels: review

#86 Scrum 59/o auth
  src/app/auth/github/page.tsx
  src/app/auth/google/page.tsx
  src/components/loader/Loader.stories.tsx
  src/components/loader/Loader.tsx
  src/components/progressBar/ProgressBar.tsx
  src/features/oauth/github/GitHubPage.tsx
  src/features/oauth/github/githubOAuth.module.scss
  src/features/oauth/google/GooglePage.tsx
  src/features/oauth/google/googleOAuth.module.scss
  src/store/Slices/appSlice.ts
  src/store/services/authApi.ts
Labels: review

#89 SCRUM-61: add z-index to CheckBox to fix incorrect displaying hover
  src/features/registration-form/RegistrationForm.tsx
  src/features/registration-form/registration.module.scss
Labels: review

#90 Scrum 59/o auth
  src/components/oauthbuttons/OAuthButtons.tsx
  src/components/oauthbuttons/googleOAuthButton/GoogleOAuthButton.tsx
  src/features/login/Login.tsx
  src/features/login/hooks/useLogin.ts
  src/features/oauth/github/GitHubPage.tsx
  src/features/oauth/google/GooglePage.tsx
Labels: review

#94 SCRUM-68: transfer logic from hooks to components
  src/features/createNewPassword/CreateNewPasswordCard.tsx
  src/features/createNewPassword/hooks/useCreateNewPassword.ts
  src/features/forgotPassword/ForgotPasswordCard.tsx
  src/features/forgotPassword/hooks/useForgotPasswordCard.ts
  src/features/link-expired-form/LinkExpiredForm.tsx
  src/features/link-expired-form/hooks/useLinkExpiredForm.ts
  src/features/login/Login.tsx
  src/features/login/hooks/useLogin.ts
  src/features/registration-confirmation-form/RegistrationConfirmationForm.tsx
  src/features/registration-confirmation-form/hooks/useRegistrationConfirmationForm.ts
  src/features/registration-form/RegistrationForm.tsx
  src/features/registration-form/hooks/useRegistrationForm.ts
Labels: review

#100 SCRUM-78 init: avatar component
  package.json
  pnpm-lock.yaml
  src/app/(account)/home/page.tsx
  src/assets/componentsIcons/ImageOutline.tsx
  src/components/avatar/AvatarBox.stories.ts
  src/components/avatar/AvatarBox.tsx
  src/components/avatar/avatar.module.scss
Labels: review

#108 Test refresh Token
  package.json
  pnpm-lock.yaml
  src/components/itemWrapper/ItemWrapper.tsx
  src/features/login/Login.tsx
  src/features/oauth/github/GitHubPage.tsx
  src/store/services/authApi.ts
  src/store/services/baseApi.ts
  src/store/store.ts
Labels: review

#102 SCRUM-79 fix: dialog add title in children
  src/components/dialog/Dialog.stories.tsx
  src/components/dialog/Dialog.tsx
  src/components/dialog/dialog.module.scss
  src/components/dialog/mock/img.png
  src/components/dialog/mock/img_coment.png
  src/components/dialog/mock/mock.tsx
Labels: review

#112 SCRUM-79:fix dialog
  src/components/dialog/Dialog.stories.tsx
  src/components/dialog/Dialog.tsx
  src/components/dialog/dialog.module.scss
Labels: review

#103 Scrum 81
  src/components/textArea/TextArea.stories.tsx
  src/components/textArea/TextArea.tsx
  src/components/textArea/textArea.module.scss
Labels: review

#99 SCRUM-20 feat: tabs
  package.json
  pnpm-lock.yaml
  src/components/tabs/Tabs.stories.tsx
  src/components/tabs/Tabs.tsx
  src/components/tabs/index.ts
  src/components/tabs/tabs.module.scss
Labels: review

#101 Scrum 77
  src/components/button/button.module.scss
  src/components/dropdown/dropdown.module.scss
  src/components/dropdown/dropdown.stories.tsx
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/dropdownItem/dropdownItem.module.scss
  src/components/dropdown/dropdownItem/dropdownItem.tsx
  src/components/header/header-mob/HeaderMobile.tsx
  src/components/header/header-mob/headerMobile.module.scss
  src/components/navigationPanel/NavigationPanel.tsx
  src/components/typography/Typography.tsx
Labels: review

#106 Scrum 72
  package.json
  pnpm-lock.yaml
  src/components/carousel/Carousel.tsx
  src/components/carousel/assets/slider.jpg
  src/components/carousel/carousel.module.scss
  src/components/carousel/carousel.stories.tsx
Labels: review

#104 SCRUM-74: add counter of registered users component
  src/components/registeredUsersCounter/RegisteredUsersCounter.stories.tsx
  src/components/registeredUsersCounter/RegisteredUsersCounter.tsx
  src/components/registeredUsersCounter/registeredUsersCounter.module.scss
Labels: review

#105 Scrum 51 (fixed version)
  src/app/layout.tsx
  src/components/header/Header.tsx
  src/store/services/authApi.ts
  src/store/services/baseApi.ts
  src/store/services/types.ts
  src/store/store.ts
Labels: review

#109 Scrum 71
  src/assets/componentsIcons/CopyOutline.tsx
  src/assets/componentsIcons/Heart.tsx
  src/assets/componentsIcons/HeartOutline.tsx
  src/assets/componentsIcons/PersonRemoveOutline.tsx
  src/components/commentsSection/modalCommentsSection.module.scss
  src/components/commentsSection/modalCommentsSection.tsx
  src/components/interactionBar/InteractionBar.stories.ts
  src/components/interactionBar/InteractionBar.tsx
  src/components/interactionBar/interactionBar.module.scss
  src/components/postLikesBox/PostLikesBox.tsx
  src/components/postLikesBox/postLikesBox.module.scss
  src/components/userAvatarName/UserAvatarName.tsx
  src/components/userAvatarName/userAvatarName.module.scss
Labels: in progress, review

#111 SCRUM-54 init : add new photo
  package.json
  pnpm-lock.yaml
  src/app/(account)/home/page.tsx
  src/components/createPost/CreatePost.stories.tsx
  src/components/createPost/CreatePost.tsx
  src/components/createPost/createPost.module.scss
  src/features/login/Login.tsx
Labels: in progress

#115 SCRUM-89 init: fix styles
  src/shared/styles/_boilerplate.scss
  src/shared/ui/postsGrid/posts.module.scss
  src/widgets/header/headerMobile/HeaderMobile.tsx
  src/widgets/header/headerWeb/HeaderWeb.tsx
  src/widgets/header/headerWeb/headerWeb.module.scss
  src/widgets/navigationPanel/sidebar/sidebar.module.scss
  src/widgets/profile/myProfile.module.scss
Labels: review
